1,TypeError,'int' object is not callable,0,,2021-11-07 15:55:34.668983,"[(b'd\x00d\x01\x83\x01F\x00d\x02S\x00', 1)]","['  File ""/usr/local/lib/python3.8/site-packages/IPython/core/interactiveshell.py"", line 3417, in run_code\n    exec(code_obj, self.user_global_ns, self.user_ns)\n', '  File ""<ipython-input-5-9b43eec38a3d>"", line 1, in <module>\n    3(2)\n']"
2,TypeError,'int' object is not callable,4,no,2021-11-07 15:55:45.702924,"[(b'd\x00d\x01\x83\x01F\x00d\x02S\x00', 1)]","['  File ""/usr/local/lib/python3.8/site-packages/IPython/core/interactiveshell.py"", line 3417, in run_code\n    exec(code_obj, self.user_global_ns, self.user_ns)\n', '  File ""<ipython-input-4-9b43eec38a3d>"", line 1, in <module>\n    3(2)\n']"
3,AttributeError,'NoneType' object has no attribute 'hello',5,no,2021-11-07 15:56:20.834872,"[(b'e\x00j\x01F\x00d\x00S\x00', 2)]","['  File ""/usr/local/lib/python3.8/site-packages/IPython/core/interactiveshell.py"", line 3417, in run_code\n    exec(code_obj, self.user_global_ns, self.user_ns)\n', '  File ""<ipython-input-5-f56079d121c5>"", line 2, in <module>\n    a.hello\n']"
4,AttributeError,'NoneType' object has no attribute 'hello',4,yes,2021-11-07 15:56:27.532666,"[(b'e\x00j\x01F\x00d\x00S\x00', 2)]","['  File ""/usr/local/lib/python3.8/site-packages/IPython/core/interactiveshell.py"", line 3417, in run_code\n    exec(code_obj, self.user_global_ns, self.user_ns)\n', '  File ""<ipython-input-6-f56079d121c5>"", line 2, in <module>\n    a.hello\n']"
5,TypeError,'int' object is not callable,0,,2021-11-07 15:57:31.542810,"[(b'd\x00d\x01\x83\x01F\x00d\x02S\x00', 1)]","['  File ""/usr/local/lib/python3.8/site-packages/IPython/core/interactiveshell.py"", line 3417, in run_code\n    exec(code_obj, self.user_global_ns, self.user_ns)\n', '  File ""<ipython-input-4-9b43eec38a3d>"", line 1, in <module>\n    3(2)\n']"
6,AttributeError,'NoneType' object has no attribute 'hello',0,,2021-11-07 15:57:34.956975,"[(b'e\x00j\x01F\x00d\x00S\x00', 2)]","['  File ""/usr/local/lib/python3.8/site-packages/IPython/core/interactiveshell.py"", line 3417, in run_code\n    exec(code_obj, self.user_global_ns, self.user_ns)\n', '  File ""<ipython-input-5-f56079d121c5>"", line 2, in <module>\n    a.hello\n']"
7,NameError,name 'data8' is not defined,0,,2021-11-07 15:57:35.415077,"[(b'e\x00F\x00d\x00S\x00', 15)]","['  File ""/usr/local/lib/python3.8/site-packages/IPython/core/interactiveshell.py"", line 3417, in run_code\n    exec(code_obj, self.user_global_ns, self.user_ns)\n', '  File ""<ipython-input-6-3551c3566c86>"", line 15, in <module>\n    data8\n']"
8,SyntaxError,"invalid syntax (<ipython-input-7-2dcb73fb32de>, line 1)",0,,2021-11-07 15:57:35.598874,"[(b't\x00|\x01|\x02|\x03|\x00j\x01t\x02B\x00d\x01\x83\x05S\x00', 101)]","['  File ""/usr/local/lib/python3.8/site-packages/IPython/core/interactiveshell.py"", line 3116, in run_cell_async\n    code_ast = compiler.ast_parse(cell, filename=cell_name)\n', '  File ""/usr/local/lib/python3.8/site-packages/IPython/core/compilerop.py"", line 101, in ast_parse\n    return compile(source, filename, symbol, self.flags | PyCF_ONLY_AST, 1)\n']"
9,AttributeError,module 'numpy' has no attribute 'aragne',0,,2021-11-07 15:57:35.775996,"[(b'e\x00\xa0\x01d\x00\xa1\x01F\x00d\x01S\x00', 1), (b'|\x00d\x01k\x02r\x18d\x02d\x00l\x00m\x01}\x01\x01\x00|\x01S\x00|\x00d\x03k\x02r0d\x04d\x05l\x01m\x02}\x02\x01\x00|\x02S\x00t\x03d\x06\xa0\x04t\x05|\x00\xa1\x02\x83\x01\x82\x01d\x00S\x00', 219)]","['  File ""/usr/local/lib/python3.8/site-packages/IPython/core/interactiveshell.py"", line 3417, in run_code\n    exec(code_obj, self.user_global_ns, self.user_ns)\n', '  File ""<ipython-input-8-2025b6fce261>"", line 1, in <module>\n    np.aragne(\'HI\')\n', '  File ""/usr/local/lib/python3.8/site-packages/numpy/__init__.py"", line 219, in __getattr__\n    raise AttributeError(""module {!r} has no attribute ""\n']"
10,IndexError,list index out of range,0,,2021-11-07 15:57:35.957290,"[(b'd\x00g\x01d\x01\x19\x00F\x00d\x02S\x00', 1)]","['  File ""/usr/local/lib/python3.8/site-packages/IPython/core/interactiveshell.py"", line 3417, in run_code\n    exec(code_obj, self.user_global_ns, self.user_ns)\n', '  File ""<ipython-input-9-31539d434322>"", line 1, in <module>\n    [2][1]\n']"
11,AttributeError,module 'numpy' has no attribute 'hi',0,,2021-11-07 15:57:36.140927,"[(b'e\x00j\x01F\x00d\x00S\x00', 1), (b'|\x00d\x01k\x02r\x18d\x02d\x00l\x00m\x01}\x01\x01\x00|\x01S\x00|\x00d\x03k\x02r0d\x04d\x05l\x01m\x02}\x02\x01\x00|\x02S\x00t\x03d\x06\xa0\x04t\x05|\x00\xa1\x02\x83\x01\x82\x01d\x00S\x00', 219)]","['  File ""/usr/local/lib/python3.8/site-packages/IPython/core/interactiveshell.py"", line 3417, in run_code\n    exec(code_obj, self.user_global_ns, self.user_ns)\n', '  File ""<ipython-input-10-f93639f3c5fa>"", line 1, in <module>\n    np.hi\n', '  File ""/usr/local/lib/python3.8/site-packages/numpy/__init__.py"", line 219, in __getattr__\n    raise AttributeError(""module {!r} has no attribute ""\n']"
12,ValueError,invalid literal for int() with base 10: 'HI',2,no,2021-11-07 15:57:36.331202,"[(b'e\x00d\x00\x83\x01F\x00d\x01S\x00', 1)]","['  File ""/usr/local/lib/python3.8/site-packages/IPython/core/interactiveshell.py"", line 3417, in run_code\n    exec(code_obj, self.user_global_ns, self.user_ns)\n', '  File ""<ipython-input-11-8921a589912c>"", line 1, in <module>\n    int(""HI"")\n']"
13,ZeroDivisionError,division by zero,3,asdf,2021-11-07 15:57:36.507918,"[(b'e\x00\x83\x00F\x00d\x00S\x00', 4), (b'd\x01d\x02\x1b\x00\x01\x00d\x00S\x00', 2)]","['  File ""/usr/local/lib/python3.8/site-packages/IPython/core/interactiveshell.py"", line 3417, in run_code\n    exec(code_obj, self.user_global_ns, self.user_ns)\n', '  File ""<ipython-input-12-84a61c95b62f>"", line 4, in <module>\n    f()\n', '  File ""<ipython-input-12-84a61c95b62f>"", line 2, in f\n    3 / 0\n']"
14,ZeroDivisionError,division by zero,3,adsfasdfasdfads,2021-11-07 15:57:36.689353,"[(b'e\x00\x83\x00F\x00d\x00S\x00', 1), (b'd\x01d\x02\x1b\x00\x01\x00d\x00S\x00', 2)]","['  File ""/usr/local/lib/python3.8/site-packages/IPython/core/interactiveshell.py"", line 3417, in run_code\n    exec(code_obj, self.user_global_ns, self.user_ns)\n', '  File ""<ipython-input-13-c43e34e6d405>"", line 1, in <module>\n    f()\n', '  File ""<ipython-input-12-84a61c95b62f>"", line 2, in f\n    3 / 0\n']"
